sudo: required
services:
  - docker


before_install:
  - docker build -t kunwar45/docker-react -f Dockerfile.dev .

script:
  - docker run kunwar45/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-538143060312"
  bucket_path: "docker-react"
  on:
    branch: master